repos:
  - repo: local
    hooks:
      - id: block-env-files
        name: Block .env and secret files
        entry: bash -c 'echo "❌  Secret-like file detected. Remove it before committing." && exit 1'
        language: system
        files: '\.(env|env\..*|key|pem)$'
